# =============================
# ðŸŒŸ Lumiere API â€“ Cloudflare Worker
# =============================
name = "lumiere-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

account_id = "493e88a4d1183b18984cfc5b311d3459"

# =============================
# ðŸ§© ConfiguraciÃ³n local (wrangler dev)
# =============================
[dev]
port = 8787

# =============================
# ðŸ§± Variables 
# =============================
[vars]
ENV = "production"

# dominios permitidos para CORS
CORS_ORIGINS = "http://localhost:4200,http://127.0.0.1:4200,https://mei-go.pages.dev,https://*.mei-go.pages.dev"

# Firebase API key (esta puede ser pÃºblica, igual que en Angular)
FIREBASE_API_KEY = "AIzaSyBhkbAf3nYulGJHThwNnH1_wIDICE3yPCQ"

# Base de la API de PayPal (OJO: api-m.sandbox, no sandbox.paypal.com)
PAYPAL_API_BASE  = "https://api-m.sandbox.paypal.com"


# =============================
# ðŸ”— Base de datos D1 (Cloudflare)
# =============================
[[d1_databases]]
binding = "DB"
database_name = "lumiere_db"
database_id = "f4ddacad-92d2-4068-9f25-81dd83a05dc5"

# =============================
# ðŸ”— KV â€” QUOTAS (lÃ­mite de significados)
# =============================
[[kv_namespaces]]
binding = "TAROT_LIMIT"
id = "48edb618e2bf4833af6cc13fcc7678d5"
preview_id = "48edb618e2bf4833af6cc13fcc7678d5"
