# =============================
# ðŸŒŸ Lumiere API â€“ Cloudflare Worker
# =============================
name = "lumiere-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# =============================
# ðŸ§© ConfiguraciÃ³n local (wrangler dev)
# =============================
[dev]
port = 8787

# =============================
# ðŸ§± Variables globales (dev + prod)
# =============================
[vars]
# Detecta automÃ¡ticamente el entorno
ENV = "production"

# OrÃ­genes permitidos tanto en local como en Pages
CORS_ORIGINS = "http://localhost:4200,http://127.0.0.1:4200,https://mei-go.pages.dev,https://6026a26f.mei-go.pages.dev"

HF_TOKEN = "@HF_TOKEN"
HF2_TOKEN = "@HF2_TOKEN"

FIREBASE_API_KEY = "AIzaSyBhkbAf3nYulGJHThwNnH1_wIDICE3yPCQ"

# =============================
# ðŸ”— Base de datos D1 (Cloudflare)
# =============================
[[d1_databases]]
binding = "DB"
database_name = "lumiere_db"
database_id = "f4ddacad-92d2-4068-9f25-81dd83a05dc5"
